//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cs_Component.Framwork {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RPFDocument {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RPFDocument() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cs_Component.Framwork.RPFDocument", typeof(RPFDocument).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه.
        /// </summary>
        internal static string LandscapeCategory {
            get {
                return ResourceManager.GetString("LandscapeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print page as landscape..
        /// </summary>
        internal static string LandscapeDescription {
            get {
                return ResourceManager.GetString("LandscapeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins.
        /// </summary>
        internal static string Margins {
            get {
                return ResourceManager.GetString("Margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه.
        /// </summary>
        internal static string MarginsCategory {
            get {
                return ResourceManager.GetString("MarginsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages&apos; margins.
        /// </summary>
        internal static string MarginsDescription {
            get {
                return ResourceManager.GetString("MarginsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع كاغذ.
        /// </summary>
        internal static string PaperKind {
            get {
                return ResourceManager.GetString("PaperKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه.
        /// </summary>
        internal static string PaperKindCategory {
            get {
                return ResourceManager.GetString("PaperKindCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع كاغذ پرينتر.
        /// </summary>
        internal static string PaperKindDescription {
            get {
                return ResourceManager.GetString("PaperKindDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپگر.
        /// </summary>
        internal static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپگر.
        /// </summary>
        internal static string PrinterCategory {
            get {
                return ResourceManager.GetString("PrinterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب يك چاپگر.
        /// </summary>
        internal static string PrinterDescription {
            get {
                return ResourceManager.GetString("PrinterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپگر.
        /// </summary>
        internal static string UseColor {
            get {
                return ResourceManager.GetString("UseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپگر.
        /// </summary>
        internal static string UseColorCategory {
            get {
                return ResourceManager.GetString("UseColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپ همراه با رنگ.
        /// </summary>
        internal static string UseColorDescription {
            get {
                return ResourceManager.GetString("UseColorDescription", resourceCulture);
            }
        }
    }
}
