//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cs_Component.Framwork {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RPFImage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RPFImage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cs_Component.Framwork.RPFImage", typeof(RPFImage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ صفحه.
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه نمايش.
        /// </summary>
        internal static string BackColorCategory {
            get {
                return ResourceManager.GetString("BackColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ پس زمينه.
        /// </summary>
        internal static string BackColorDescription {
            get {
                return ResourceManager.GetString("BackColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ.
        /// </summary>
        internal static string BorderColor {
            get {
                return ResourceManager.GetString("BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاشيه.
        /// </summary>
        internal static string BorderColorCategory {
            get {
                return ResourceManager.GetString("BorderColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ حاشيه.
        /// </summary>
        internal static string BorderColorDescription {
            get {
                return ResourceManager.GetString("BorderColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins.
        /// </summary>
        internal static string BorderMargin {
            get {
                return ResourceManager.GetString("BorderMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاشيه.
        /// </summary>
        internal static string BorderMarginCategory {
            get {
                return ResourceManager.GetString("BorderMarginCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins from the border.
        /// </summary>
        internal static string BorderMarginDescription {
            get {
                return ResourceManager.GetString("BorderMarginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string BorderPadding {
            get {
                return ResourceManager.GetString("BorderPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاشيه.
        /// </summary>
        internal static string BorderPaddingCategory {
            get {
                return ResourceManager.GetString("BorderPaddingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding from the border.
        /// </summary>
        internal static string BorderPaddingDescription {
            get {
                return ResourceManager.GetString("BorderPaddingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه.
        /// </summary>
        internal static string BorderSize {
            get {
                return ResourceManager.GetString("BorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاشيه.
        /// </summary>
        internal static string BorderSizeCategory {
            get {
                return ResourceManager.GetString("BorderSizeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه حاشيه.
        /// </summary>
        internal static string BorderSizeDescription {
            get {
                return ResourceManager.GetString("BorderSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عكس.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه نمايش.
        /// </summary>
        internal static string ImageCategory {
            get {
                return ResourceManager.GetString("ImageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عكس مربوطه.
        /// </summary>
        internal static string ImageDescription {
            get {
                return ResourceManager.GetString("ImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرح.
        /// </summary>
        internal static string LocationCategory {
            get {
                return ResourceManager.GetString("LocationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object&apos;s position related to container.
        /// </summary>
        internal static string LocationDescription {
            get {
                return ResourceManager.GetString("LocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio.
        /// </summary>
        internal static string PreserveAspectRatio {
            get {
                return ResourceManager.GetString("PreserveAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه نمايش.
        /// </summary>
        internal static string PreserveAspectRatioCategory {
            get {
                return ResourceManager.GetString("PreserveAspectRatioCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set true to preserve the image&apos;s aspect ratio..
        /// </summary>
        internal static string PreserveAspectRatioDescription {
            get {
                return ResourceManager.GetString("PreserveAspectRatioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرح.
        /// </summary>
        internal static string SizeCategory {
            get {
                return ResourceManager.GetString("SizeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه شئ.
        /// </summary>
        internal static string SizeDescription {
            get {
                return ResourceManager.GetString("SizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شفافيت.
        /// </summary>
        internal static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه نمايش.
        /// </summary>
        internal static string TransparencyCategory {
            get {
                return ResourceManager.GetString("TransparencyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image&apos;s transparency : 0= opaque 100= transparent.
        /// </summary>
        internal static string TransparencyDescription {
            get {
                return ResourceManager.GetString("TransparencyDescription", resourceCulture);
            }
        }
    }
}
