//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cs_Component.Framwork {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RPFSection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RPFSection() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cs_Component.Framwork.RPFSection", typeof(RPFSection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ صفحه.
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه نمايش.
        /// </summary>
        internal static string BackColorCategory {
            get {
                return ResourceManager.GetString("BackColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ پس زمينه.
        /// </summary>
        internal static string BackColorDescription {
            get {
                return ResourceManager.GetString("BackColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ.
        /// </summary>
        internal static string BorderColor {
            get {
                return ResourceManager.GetString("BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاشيه.
        /// </summary>
        internal static string BorderColorCategory {
            get {
                return ResourceManager.GetString("BorderColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ حاشيه.
        /// </summary>
        internal static string BorderColorDescription {
            get {
                return ResourceManager.GetString("BorderColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاشيه دار كردن.
        /// </summary>
        internal static string BorderMargin {
            get {
                return ResourceManager.GetString("BorderMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاشيه.
        /// </summary>
        internal static string BorderMarginCategory {
            get {
                return ResourceManager.GetString("BorderMarginCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins from the border.
        /// </summary>
        internal static string BorderMarginDescription {
            get {
                return ResourceManager.GetString("BorderMarginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه.
        /// </summary>
        internal static string BorderSize {
            get {
                return ResourceManager.GetString("BorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاشيه.
        /// </summary>
        internal static string BorderSizeCategory {
            get {
                return ResourceManager.GetString("BorderSizeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه حاشيه.
        /// </summary>
        internal static string BorderSizeDescription {
            get {
                return ResourceManager.GetString("BorderSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External margins.
        /// </summary>
        internal static string ExtMargin {
            get {
                return ResourceManager.GetString("ExtMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ط‌رح‌.
        /// </summary>
        internal static string ExtMarginCategory {
            get {
                return ResourceManager.GetString("ExtMarginCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section&apos;s external margins..
        /// </summary>
        internal static string ExtMarginDescription {
            get {
                return ResourceManager.GetString("ExtMarginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه نمايش.
        /// </summary>
        internal static string NameCategory {
            get {
                return ResourceManager.GetString("NameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام محدوده.
        /// </summary>
        internal static string NameDescription {
            get {
                return ResourceManager.GetString("NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه.
        /// </summary>
        internal static string VerticalSize {
            get {
                return ResourceManager.GetString("VerticalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ط‌رح‌.
        /// </summary>
        internal static string VerticalSizeCategory {
            get {
                return ResourceManager.GetString("VerticalSizeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه عمودي‌ بخش.
        /// </summary>
        internal static string VerticalSizeDescription {
            get {
                return ResourceManager.GetString("VerticalSizeDescription", resourceCulture);
            }
        }
    }
}
