//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cs_Component.Framwork {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cs_Component.Framwork.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جعبه.
        /// </summary>
        internal static string id_designer_box_tree_node {
            get {
                return ResourceManager.GetString("id_designer_box_tree_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين گزارش قابل كپي شدن نيست !.
        /// </summary>
        internal static string id_designer_cannot_copy_doc {
            get {
                return ResourceManager.GetString("id_designer_cannot_copy_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين گزارش قابل حذف شدن نيست.
        /// </summary>
        internal static string id_designer_cannot_delete_doc {
            get {
                return ResourceManager.GetString("id_designer_cannot_delete_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه ها.
        /// </summary>
        internal static string id_designer_container_tree_node {
            get {
                return ResourceManager.GetString("id_designer_container_tree_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيتم هاي موجود گزارش.
        /// </summary>
        internal static string id_designer_document_tree_node {
            get {
                return ResourceManager.GetString("id_designer_document_tree_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشياء پويا.
        /// </summary>
        internal static string id_designer_dynamic_tree_node {
            get {
                return ResourceManager.GetString("id_designer_dynamic_tree_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عكس.
        /// </summary>
        internal static string id_designer_image_tree_node {
            get {
                return ResourceManager.GetString("id_designer_image_tree_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        internal static string id_designer_label_tree_node {
            get {
                return ResourceManager.GetString("id_designer_label_tree_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط.
        /// </summary>
        internal static string id_designer_line_tree_node {
            get {
                return ResourceManager.GetString("id_designer_line_tree_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيتم انتخاب شده حذف ميشود ..مايل به ادامه هستيد؟.
        /// </summary>
        internal static string id_designer_prompt_delete {
            get {
                return ResourceManager.GetString("id_designer_prompt_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدوده ثابت.
        /// </summary>
        internal static string id_designer_section_tree_node {
            get {
                return ResourceManager.GetString("id_designer_section_tree_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشياء ايستا.
        /// </summary>
        internal static string id_designer_static_tree_node {
            get {
                return ResourceManager.GetString("id_designer_static_tree_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول.
        /// </summary>
        internal static string id_designer_table_tree_node {
            get {
                return ResourceManager.GetString("id_designer_table_tree_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده ها.
        /// </summary>
        internal static string id_designer_variable_tree_node {
            get {
                return ResourceManager.GetString("id_designer_variable_tree_node", resourceCulture);
            }
        }
    }
}
